name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: frontend submodule
      run: |
        git submodule init
        git submodule update
    - name: npm install
      run: |
        npm install --prefix frontend
        npm install --prefix functions
        npm install -g firebase-tools
    - name: firebase deploy
      run: |
        firebase deploy --project dhbw-lecture-scheduler --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        CI: true
